serviceName: bank
servicePort: 9090
logging:
  level: -1
  timeFormat: 2006-01-02T15:04:05Z07:00
security:
  tlsCert: /Users/jessegitaka/Desktop/bank/certs/localhost/cert.pem
  tlsKey: /Users/jessegitaka/Desktop/bank/certs/localhost/key.pem
  serverName: localhost
databases:
  sqlDatabase:
    required: true
    address: localhost:3306
    host: localhost
    port: 3306
    user: root
    schema: banky
    password: hakty11
    userFile: ./user
    schemaFile: ./schema
    passwordFile: ./password
    metadata:
      name: mysql
      dialect: mysql
      orm: gorm
  redisDatabase:
    required: false
    address: localhost:6379
    host: localhost
    port: 6379
    metadata:
      name: redis
      useRediSearch: false

# externalServices:
# - name: authentication
#   type: Authentication
#   required: true
#   address: localhost:5600
#   host: localhost
#   port: 5600
#   tlsCert: /home/gideon/.secrets/keys/cert.pem
#   serverName: localhost
